#!/usr/bin/env php
<?php

// prevent access from web
if (PHP_SAPI !== 'cli') {
    echo "Tarsius";
    exit;
}

// Autoloader
require __DIR__.'/vendor/autoload.php';
// set global constant
define('DIR', __DIR__);
// Tarsius Version
define('TAR_VERSION', '1.3.2');

$tarsius = SLiMSTarsius\Tarmagick::startup(DIR);
